//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 02:04:00 PM CEST 
//


package eu.erasmuswithoutpaper.api.echo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hei-id" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{https://github.com/erasmus-without-paper/ewp-specs-api-echo/blob/master/request-vars.xsd}vars"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "heiId",
    "vars"
})
@XmlRootElement(name = "response", namespace = "https://github.com/erasmus-without-paper/ewp-specs-api-echo/tree/master")
public class Response {

    @XmlElement(name = "hei-id", namespace = "https://github.com/erasmus-without-paper/ewp-specs-api-echo/tree/master")
    protected List<String> heiId;
    @XmlElement(required = true)
    protected Vars vars;

    /**
     * Gets the value of the heiId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the heiId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHeiId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getHeiId() {
        if (heiId == null) {
            heiId = new ArrayList<String>();
        }
        return this.heiId;
    }

    /**
     * 
     *                             The value of the `echo` variable from the request. Note, that you must use the
     *                             https://github.com/erasmus-without-paper/ewp-specs-api-echo/blob/master/request-vars.xsd
     *                             XML namespace for this element!
     *                         
     * 
     * @return
     *     possible object is
     *     {@link Vars }
     *     
     */
    public Vars getVars() {
        return vars;
    }

    /**
     * Sets the value of the vars property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vars }
     *     
     */
    public void setVars(Vars value) {
        this.vars = value;
    }

}
